services:
  mysql-db:
    image: mysql:8.0 # Spécifier la version MySQL 8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # Permet l'absence de mot de passe pour root
      MYSQL_DATABASE: cat_db # Base de données à créer
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  api:
    image: cat-api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql-db # Nom du service MySQL dans Docker Compose
      DB_USER: root
      DB_PASSWORD: "" # Pas de mot de passe
      DB_NAME: cat_db
    depends_on:
      - mysql-db # Assurez-vous que MySQL est démarré avant l'API
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
